### ISSUE TITLE
unecpected error

### ISSUE THREAD

**Issue by jrgnbrggr** [DP-3T/dp3t-app-ios-ch#117] opened 2020-06-12 20:56 UTC
![38A5C841-76B6-4888-9B00-1B0F401053E2](https://user-images.githubusercontent.com/66848899/84545639-e3ff0380-acff-11ea-926c-844118078ece.png)

**Comment by habi** [comment] 2020-06-15 08:46
Possibly a duplicate of https://github.com/DP-3T/dp3t-app-ios-ch/issues/109

**Comment by stmitt** [comment] 2020-06-24 11:31
This issue has been resolved with the newest SDK version. Thanks for your feedback!

**Closed by stmitt** 2020-06-24 11:31 UTC
