### ISSUE TITLE
Geofencing active: Exposure Notification Region Changed

### ISSUE THREAD

**Issue by aschlapbach** [DP-3T/dp3t-app-ios-ch#127] opened 2020-06-16 07:48 UTC
Using Ver. 1.0.3 (200612.2347.141) on iPhone X running iOS 13.5.1 with Swisscom 41.0 plan, I get every few days a warning "Exposure Notification Region Changed: COVID-19 Exposure Notifications may not be supported by “SwissCovid” in this region. You should confirm which app you are using in Settings.".

Warning seems to come up in the area of Lake of Zurich (twice in Thalwil, once on the Ferry Meilen>Horgen mid-lake) while on 4G. Last warning was 2020-06-15 at 1708h UTC on the ferry.

Unclear if warning comes from app itself or from OS API. In any case, it implicitly and explicitly is a (wrongly working) geofencing issue and a s a such may trigger public concerns of a violation of "no GPS used" statements (although it does not look to refer to the core BT/hash function).

![exp_notif_reg_cng](https://user-images.githubusercontent.com/66993559/84745826-6a903b00-afb5-11ea-8d69-026425d9f311.jpg)

**Comment by martinsteiger** [comment] 2020-06-16 09:45
Seconded. The issue is most likely caused by Apple's API / framework because it also occurs with other PT apps such as Immuni (Italy).

**Comment by gabrielwalt** [comment] 2020-06-30 04:42
This notification pops up constantly and is very annoying. It provides the impression that the app isn’t working because of some misconfigured settings.

**Comment by aschlapbach** [comment] 2020-06-30 05:57
> This notification pops up constantly and is very annoying. It provides the impression that the app isn’t working because of some misconfigured settings.

Yes. I get the notification also with the released app.

Looks like there is marginal activity in this GitHub.

**Comment by UBaggeler** [comment] 2020-06-30 11:39
This is a bug of iOS 13.5.x which should get fixed with iOS 13.6 (currently still in beta). Nothing we can do from our side.

**Comment by UBaggeler** [comment] 2020-07-15 19:29
iOS 13.6 was released by Apple a few hours ago. Please reopen this issue if you get see this popup again.

**Closed by UBaggeler** 2020-07-15 19:29 UTC
Labels: bug
