### ISSUE TITLE
Proximity tracing cannot be activated on iOS 14 public beta

### ISSUE THREAD

**Issue by arjunmuralidharan** [DP-3T/dp3t-app-ios-ch#193] opened 2020-07-11 11:36 UTC
The public beta of iOS 14 was released last week. The SwissCovid app does not appear to support iOS 14 as contact tracing cannot be activated. The iOS settings claim that exposure logging is not available. 

I presume this issue is significant as the public beta is used by potentially thousands of phones in Switzerland. I don’t know if this is an issue with the entitlements from Apple and if it can be solved without Apple’s involvement.

**Comment by mosea3** [comment] 2020-07-11 12:10
Its exactly what UBaggeler stated yesterday:

> This is a bug in iOS 13.5.x. According to Apple this issue should be fixed in the next version of iOS (13.6 beta currently available).

Using trial software always brings the risk of having unfunctional software. Thus, shouldnt be installed by non-developers.

**Comment by UBaggeler** [comment] 2020-07-15 20:29
Duplicate of https://github.com/DP-3T/dp3t-app-ios-ch/issues/187

**Closed** 2020-07-17 10:46 UTC
