### ISSUE TITLE
SwissCovid app broke after device upgrade to iOS 14.0

### ISSUE THREAD

**Issue by amlinux** [DP-3T/dp3t-app-ios-ch#217] opened 2020-07-17 19:31 UTC
In the app I see "Proximity tracing deactivated" and "COVID-19 Exposure Logging and Notifications are not available in your region". Device region is Switzerland.

![IMG_5967](https://user-images.githubusercontent.com/449322/87823983-bcf29f00-c874-11ea-95ad-b329dcb91636.PNG)

![IMG_5968](https://user-images.githubusercontent.com/449322/87823985-bd8b3580-c874-11ea-92d8-eb53d15b9fcd.PNG)

![IMG_5969](https://user-images.githubusercontent.com/449322/87823986-bd8b3580-c874-11ea-89d3-ebbc245f2737.PNG)

![IMG_5970](https://user-images.githubusercontent.com/449322/87823989-be23cc00-c874-11ea-9b88-9a573fe0d247.PNG)

![IMG_5972](https://user-images.githubusercontent.com/449322/87823990-be23cc00-c874-11ea-9bd0-e8d6e9649d06.PNG)

**Comment by clivazpat** [comment] 2020-07-20 06:54
It looks like it’s ‘normal’ since the actual iOS 14 beta doesn’t include ExposureNotification API.


![](https://cdn-mgig-fr.cdn.ampproject.org/i/s/cdn.mgig.fr/2020/07/mg-5448c8c2-3351-46a9-8d37-w1000h798-sc.jpg)

**Comment by UBaggeler** [comment] 2020-07-20 07:00
Duplicate of #187

**Closed** 2020-07-20 13:34 UTC
